baseURL = "https://example.com/"
languageCode = "es-mx"
title = "Posts"
enableRobotsTXT = true

[pagination]
  pagerSize = 20

[taxonomies]
  tag = "tags"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "Inicio"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "Archivos"
    pageRef = "/archives"
    weight = 2
  [[menu.main]]
    name = "Tags"
    pageRef = "/tags"
    weight = 3


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
