baseURL = "https://example.com/"
languageCode = "es-mx"
timeZone = "America/Mexico_City"
title = "betancourt"
enableRobotsTXT = true

[pagination]
  pagerSize = 20

[taxonomies]
  tag = "tags"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "Inicio"
    pageRef = "/"
    weight = 1
  [[menu.main]]
    name = "Sobre mí"
    pageRef = "/about"
    weight = 2
  [[menu.main]]
    name = "Profesional"
    pageRef = "/proyectos-profesionales"
    weight = 3
  [[menu.main]]
    name = "Académico"
    pageRef = "/proyectos-academicos"
    weight = 4
  [[menu.main]]
    name = "Escritos"
    pageRef = "/posts"
    weight = 5
  [[menu.main]]
    name = "Zettelkasten"
    pageRef = "/zettelkasten"
    weight = 6
  [[menu.main]]
    name = "Lit"
    pageRef = "/lit"
    weight = 7
  [[menu.main]]
    name = "CV"
    pageRef = "/cv"
    weight = 8

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
